# Welcome to Jekyll!

# Website settings
title: Home
description: Parth Parnerkar's portfolio
keywords: Parth, Parth Parnerkar, Network Engineer, Computer Networking, SDN
baseurl:  /Jalpc # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://parthparnerkar.github.io/   # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Parth Parnerkar  # Be used at blog posts' author.
  first_name: Parth  # Be used at index page about me section.
  last_name: Parnerkar  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: ParthParnerkar  # Leave blank if you don't have now
  linkedin_id: parthparnerkar # Leave blank if you don't have now
  facebook_username: parthparnerkar  # Leave blank if you don't have now
  twitter_username: Placid_Parth  # Leave blank if you don't have now
  email: parthparnerkar123@gmail.com  # Leave blank if you don't have now
  cv: https://drive.google.com/drive/u/0/folders/1B3-nig0g7vnq5I5iQ76tpUwptlbpfios # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  #skill_icon1:
   # - name: icon-apache
   # - name: fa-linux
  #skill_icon2:
   # - name: fa-linux
   # - name: icon-apache
  desc: I am a Graduate Student pursuing my Masters in Telecommunications from Rochester Institute of Technology. 
        My specialization is in Computer Networking, more specifically towards Software Defined Networking.
        I am currently involved in research related to Security in a SDN infrastucture 
        I have previously worked with New York Power Authority as a Developmental Intern for the Network Services team at the White Plains Office.
  

# comment
#disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  #name: jalpc

# analytics
## google analytics
#ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  #id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

